import cdms2
f=cdms2.open('SSU.nc')
tb=f('tb')
tb.shape
time=tb.getTime()
latitude=tb.getLatitude()
longitude=tb.getLongitude()
ssu1 = cdms2.createVariable( tb[:,0,:,:],axes=[time,latitude,longitude],id='ssu1' )
ssu2 = cdms2.createVariable( tb[:,1,:,:],axes=[time,latitude,longitude],id='ssu2' )
ssu3 = cdms2.createVariable( tb[:,2,:,:],axes=[time,latitude,longitude],id='ssu3' )
cdms2.setNetcdfShuffleFlag(0)
cdms2.setNetcdfDeflateFlag(0)
cdms2.setNetcdfDeflateLevelFlag(0)
cdms2.setNetcdf4Flag(0)
g=cdms2.open('SSU1.nc','w')
g.write(ssu1)
g.close()
g=cdms2.open('SSU2.nc','w')
g.write(ssu2)
g.close()
g=cdms2.open('SSU3.nc','w')
g.write(ssu3)
g.close()
